//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsBetter.Test.WSReporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSReporte.IReporteService")]
    public interface IReporteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteService/GenerarReporteTorneo", ReplyAction="http://tempuri.org/IReporteService/GenerarReporteTorneoResponse")]
        System.Collections.Generic.List<WhoIsBetter.Entity.ReporteTorneo> GenerarReporteTorneo(int idTorneo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteService/GenerarReporteTorneo", ReplyAction="http://tempuri.org/IReporteService/GenerarReporteTorneoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.ReporteTorneo>> GenerarReporteTorneoAsync(int idTorneo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporteServiceChannel : WhoIsBetter.Test.WSReporte.IReporteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteServiceClient : System.ServiceModel.ClientBase<WhoIsBetter.Test.WSReporte.IReporteService>, WhoIsBetter.Test.WSReporte.IReporteService {
        
        public ReporteServiceClient() {
        }
        
        public ReporteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WhoIsBetter.Entity.ReporteTorneo> GenerarReporteTorneo(int idTorneo) {
            return base.Channel.GenerarReporteTorneo(idTorneo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.ReporteTorneo>> GenerarReporteTorneoAsync(int idTorneo) {
            return base.Channel.GenerarReporteTorneoAsync(idTorneo);
        }
    }
}
