//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsBetter.Test.WSContendor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSContendor.IContendorService")]
    public interface IContendorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/CrearContendor", ReplyAction="http://tempuri.org/IContendorService/CrearContendorResponse")]
        int CrearContendor(WhoIsBetter.Entity.Contendor contendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/CrearContendor", ReplyAction="http://tempuri.org/IContendorService/CrearContendorResponse")]
        System.Threading.Tasks.Task<int> CrearContendorAsync(WhoIsBetter.Entity.Contendor contendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ObtenerContendor", ReplyAction="http://tempuri.org/IContendorService/ObtenerContendorResponse")]
        WhoIsBetter.Entity.Contendor ObtenerContendor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ObtenerContendor", ReplyAction="http://tempuri.org/IContendorService/ObtenerContendorResponse")]
        System.Threading.Tasks.Task<WhoIsBetter.Entity.Contendor> ObtenerContendorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ActualizarContendor", ReplyAction="http://tempuri.org/IContendorService/ActualizarContendorResponse")]
        void ActualizarContendor(WhoIsBetter.Entity.Contendor contendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ActualizarContendor", ReplyAction="http://tempuri.org/IContendorService/ActualizarContendorResponse")]
        System.Threading.Tasks.Task ActualizarContendorAsync(WhoIsBetter.Entity.Contendor contendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/EliminarContendor", ReplyAction="http://tempuri.org/IContendorService/EliminarContendorResponse")]
        void EliminarContendor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/EliminarContendor", ReplyAction="http://tempuri.org/IContendorService/EliminarContendorResponse")]
        System.Threading.Tasks.Task EliminarContendorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ListarContendores", ReplyAction="http://tempuri.org/IContendorService/ListarContendoresResponse")]
        System.Collections.Generic.List<WhoIsBetter.Entity.Contendor> ListarContendores(int idTorneo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContendorService/ListarContendores", ReplyAction="http://tempuri.org/IContendorService/ListarContendoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.Contendor>> ListarContendoresAsync(int idTorneo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContendorServiceChannel : WhoIsBetter.Test.WSContendor.IContendorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContendorServiceClient : System.ServiceModel.ClientBase<WhoIsBetter.Test.WSContendor.IContendorService>, WhoIsBetter.Test.WSContendor.IContendorService {
        
        public ContendorServiceClient() {
        }
        
        public ContendorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContendorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContendorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContendorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearContendor(WhoIsBetter.Entity.Contendor contendor) {
            return base.Channel.CrearContendor(contendor);
        }
        
        public System.Threading.Tasks.Task<int> CrearContendorAsync(WhoIsBetter.Entity.Contendor contendor) {
            return base.Channel.CrearContendorAsync(contendor);
        }
        
        public WhoIsBetter.Entity.Contendor ObtenerContendor(int id) {
            return base.Channel.ObtenerContendor(id);
        }
        
        public System.Threading.Tasks.Task<WhoIsBetter.Entity.Contendor> ObtenerContendorAsync(int id) {
            return base.Channel.ObtenerContendorAsync(id);
        }
        
        public void ActualizarContendor(WhoIsBetter.Entity.Contendor contendor) {
            base.Channel.ActualizarContendor(contendor);
        }
        
        public System.Threading.Tasks.Task ActualizarContendorAsync(WhoIsBetter.Entity.Contendor contendor) {
            return base.Channel.ActualizarContendorAsync(contendor);
        }
        
        public void EliminarContendor(int id) {
            base.Channel.EliminarContendor(id);
        }
        
        public System.Threading.Tasks.Task EliminarContendorAsync(int id) {
            return base.Channel.EliminarContendorAsync(id);
        }
        
        public System.Collections.Generic.List<WhoIsBetter.Entity.Contendor> ListarContendores(int idTorneo) {
            return base.Channel.ListarContendores(idTorneo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.Contendor>> ListarContendoresAsync(int idTorneo) {
            return base.Channel.ListarContendoresAsync(idTorneo);
        }
    }
}
