//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsBetter.WSREST.WSParticipante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSParticipante.IParticipanteService")]
    public interface IParticipanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/InscribirParticipante", ReplyAction="http://tempuri.org/IParticipanteService/InscribirParticipanteResponse")]
        int InscribirParticipante(int idTorneo, WhoIsBetter.Entity.Participante participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/InscribirParticipante", ReplyAction="http://tempuri.org/IParticipanteService/InscribirParticipanteResponse")]
        System.Threading.Tasks.Task<int> InscribirParticipanteAsync(int idTorneo, WhoIsBetter.Entity.Participante participante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParticipanteServiceChannel : WhoIsBetter.WSREST.WSParticipante.IParticipanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParticipanteServiceClient : System.ServiceModel.ClientBase<WhoIsBetter.WSREST.WSParticipante.IParticipanteService>, WhoIsBetter.WSREST.WSParticipante.IParticipanteService {
        
        public ParticipanteServiceClient() {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InscribirParticipante(int idTorneo, WhoIsBetter.Entity.Participante participante) {
            return base.Channel.InscribirParticipante(idTorneo, participante);
        }
        
        public System.Threading.Tasks.Task<int> InscribirParticipanteAsync(int idTorneo, WhoIsBetter.Entity.Participante participante) {
            return base.Channel.InscribirParticipanteAsync(idTorneo, participante);
        }
    }
}
