//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsBetter.WSREST.WSFavorito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFavorito.IFavoritoService")]
    public interface IFavoritoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritoService/CrearFavorito", ReplyAction="http://tempuri.org/IFavoritoService/CrearFavoritoResponse")]
        void CrearFavorito(WhoIsBetter.Entity.Favorito favorito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritoService/CrearFavorito", ReplyAction="http://tempuri.org/IFavoritoService/CrearFavoritoResponse")]
        System.Threading.Tasks.Task CrearFavoritoAsync(WhoIsBetter.Entity.Favorito favorito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritoService/ListarFavoritos", ReplyAction="http://tempuri.org/IFavoritoService/ListarFavoritosResponse")]
        System.Collections.Generic.List<WhoIsBetter.Entity.Favorito> ListarFavoritos(int idTorneo, int idParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritoService/ListarFavoritos", ReplyAction="http://tempuri.org/IFavoritoService/ListarFavoritosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.Favorito>> ListarFavoritosAsync(int idTorneo, int idParticipante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFavoritoServiceChannel : WhoIsBetter.WSREST.WSFavorito.IFavoritoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FavoritoServiceClient : System.ServiceModel.ClientBase<WhoIsBetter.WSREST.WSFavorito.IFavoritoService>, WhoIsBetter.WSREST.WSFavorito.IFavoritoService {
        
        public FavoritoServiceClient() {
        }
        
        public FavoritoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FavoritoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FavoritoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FavoritoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearFavorito(WhoIsBetter.Entity.Favorito favorito) {
            base.Channel.CrearFavorito(favorito);
        }
        
        public System.Threading.Tasks.Task CrearFavoritoAsync(WhoIsBetter.Entity.Favorito favorito) {
            return base.Channel.CrearFavoritoAsync(favorito);
        }
        
        public System.Collections.Generic.List<WhoIsBetter.Entity.Favorito> ListarFavoritos(int idTorneo, int idParticipante) {
            return base.Channel.ListarFavoritos(idTorneo, idParticipante);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WhoIsBetter.Entity.Favorito>> ListarFavoritosAsync(int idTorneo, int idParticipante) {
            return base.Channel.ListarFavoritosAsync(idTorneo, idParticipante);
        }
    }
}
